import 'package:flutter/material.dart';
import 'package:flutterapp/test_201app/generatedhomescreenwidget/generated/GeneratedFastfoodButtonWidget.dart';
import 'package:flutterapp/test_201app/generatedhomescreenwidget/generated/GeneratedDELICIOUSFOODATYOURDOORSTEPSWidget.dart';
import 'package:flutterapp/test_201app/generatedhomescreenwidget/generated/GeneratedShoppingcarticonWidget.dart';
import 'package:flutterapp/test_201app/generatedhomescreenwidget/generated/GeneratedDrinksButtonWidget.dart';
import 'package:flutterapp/test_201app/generatedhomescreenwidget/generated/GeneratedRectangle11Widget.dart';
import 'package:flutterapp/test_201app/generatedhomescreenwidget/generated/GeneratedZingercardWidget.dart';
import 'package:flutterapp/test_201app/generatedhomescreenwidget/generated/GeneratedMenuiconWidget.dart';
import 'package:flutterapp/test_201app/generatedhomescreenwidget/generated/GeneratedRectangle11Widget1.dart';
import 'package:flutterapp/test_201app/generatedhomescreenwidget/generated/GeneratedRiceButtonWidget.dart';
import 'package:flutterapp/test_201app/generatedhomescreenwidget/generated/GeneratedChickenManchurianWidget.dart';
import 'package:flutterapp/test_201app/generatedhomescreenwidget/generated/GeneratedSearchWidget.dart';
import 'package:flutterapp/test_201app/generatedhomescreenwidget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/test_201app/generatedhomescreenwidget/generated/GeneratedRectangle10Widget.dart';
import 'package:flutterapp/test_201app/generatedhomescreenwidget/generated/GeneratedPopularNowWidget.dart';
import 'package:flutterapp/test_201app/generatedhomescreenwidget/generated/GeneratedVector3Widget.dart';
import 'package:flutterapp/test_201app/generatedhomescreenwidget/generated/GeneratedChineseCuisineWidget.dart';
import 'package:flutterapp/test_201app/generatedhomescreenwidget/generated/GeneratedGroupWidget.dart';
import 'package:flutterapp/test_201app/generatedhomescreenwidget/generated/GeneratedAllfooditemsButtonWidget.dart';
import 'package:flutterapp/test_201app/generatedhomescreenwidget/generated/GeneratedRicecardWidget.dart';
import 'package:flutterapp/test_201app/generatedhomescreenwidget/generated/Generated\$11050Widget.dart';

/* Frame Home Screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeScreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(20.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(20.0),
                child: Container(
                  color: Color.fromARGB(255, 242, 243, 248),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 531.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 200.0,
                top: 222.0,
                right: null,
                bottom: null,
                width: 66.0,
                height: 66.0,
                child: GeneratedFastfoodButtonWidget(),
              ),
              Positioned(
                left: 30.0,
                top: 714.0,
                right: null,
                bottom: null,
                width: 72.0,
                height: 72.0,
                child: GeneratedRectangle11Widget(),
              ),
              Positioned(
                left: 17.0,
                top: 110.0,
                right: null,
                bottom: null,
                width: 265.0,
                height: 67.0,
                child: GeneratedDELICIOUSFOODATYOURDOORSTEPSWidget(),
              ),
              Positioned(
                left: 18.0,
                top: 648.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 33.0,
                child: GeneratedPopularNowWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 706.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 87.0,
                child: GeneratedRectangle10Widget(),
              ),
              Positioned(
                left: 118.0,
                top: 714.0,
                right: null,
                bottom: null,
                width: 179.0,
                height: 20.0,
                child: GeneratedChickenManchurianWidget(),
              ),
              Positioned(
                left: 118.0,
                top: 737.0,
                right: null,
                bottom: null,
                width: 179.0,
                height: 12.0,
                child: GeneratedChineseCuisineWidget(),
              ),
              Positioned(
                left: 304.0,
                top: 731.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 38.0,
                child: GeneratedRectangle11Widget1(),
              ),
              Positioned(
                left: 327.0,
                top: 743.0,
                right: null,
                bottom: null,
                width: 7.999999523162842,
                height: 15.0,
                child: GeneratedVector3Widget(),
              ),
              Positioned(
                left: 118.0,
                top: 761.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 30.0,
                child: Generated$11050Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 335.0,
                right: null,
                bottom: null,
                width: 194.0,
                height: 286.0,
                child: GeneratedRicecardWidget(),
              ),
              Positioned(
                left: 246.0,
                top: 335.0,
                right: null,
                bottom: null,
                width: 194.0,
                height: 286.0,
                child: GeneratedZingercardWidget(),
              ),
              Positioned(
                left: 110.0,
                top: 222.0,
                right: null,
                bottom: null,
                width: 66.0,
                height: 66.0,
                child: GeneratedRiceButtonWidget(),
              ),
              Positioned(
                left: 220.0,
                top: 241.0,
                right: null,
                bottom: null,
                width: 26.0,
                height: 26.0,
                child: GeneratedGroupWidget(),
              ),
              Positioned(
                left: 290.0,
                top: 222.0,
                right: null,
                bottom: null,
                width: 66.0,
                height: 66.0,
                child: GeneratedDrinksButtonWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 39.0,
                right: null,
                bottom: null,
                width: 29.0,
                height: 15.0,
                child: GeneratedMenuiconWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 222.0,
                right: null,
                bottom: null,
                width: 66.0,
                height: 66.0,
                child: GeneratedAllfooditemsButtonWidget(),
              ),
              Positioned(
                left: 301.0,
                top: 42.0,
                right: null,
                bottom: null,
                width: 14.999994277954102,
                height: 16.000024795532227,
                child: GeneratedSearchWidget(),
              ),
              Positioned(
                left: 340.0,
                top: 38.0,
                right: null,
                bottom: null,
                width: 15.109999656677246,
                height: 19.741178512573242,
                child: GeneratedShoppingcarticonWidget(),
              )
            ]),
      ),
    ));
  }
}
